#!/bin/bash
#SBATCH -A SMU-Math-6370    # account name
#SBATCH -J q_omp_t10    # job name
#SBATCH -o t10_out.%j        # output file
#SBATCH -N 1                # total nodes requested
#SBATCH -n 1                # total MPI tasks requested
#SBATCH -p serial           # queue name
#SBATCH -t 24:00:00         # total time requested <hh:mm:ss>

export OMP_NUM_THREADS=1
ibrun ./quadjac -N=160 -M=40

