#!/bin/bash
#SBATCH -J p1_mf.job                # job name
#SBATCH -o output_maneframe_1.txt   # output/error file
#SBATCH -n 1                        # requested MPI tasks
#SBATCH --ntasks-per-node=1         # maximum task load per node
#SBATCH -p parallel-short           # requested queue
#SBATCH -t 1                        # maximum runtime in minutes
#SBATCH --exclusive                 # do not share nodes

srun ./driver.exe

