###################################################################
#  Makefile for Lab 1
#
#  Daniel R. Reynolds
#  SMU Mathematics
#  Math 6370
#  2 January 2009
###################################################################

main.exe : main.cpp
	g++ -o main.exe main.cpp



####### End of Makefile #######
