driver.exe :
	g++ -c driver.cpp one_norm.cpp vector_difference.cpp vector_product.cpp vector_sum.cpp	
	g++ -o driver.exe driver.o one_norm.o vector_difference.o vector_product.o vector_sum.o

clean : 
	rm -f *.o
